#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLIKHACHSAN
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_Doi7(3)")]
	public partial class DBQuanLiKhachSanDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_CTHoaDon(tbl_CTHoaDon instance);
    partial void Updatetbl_CTHoaDon(tbl_CTHoaDon instance);
    partial void Deletetbl_CTHoaDon(tbl_CTHoaDon instance);
    partial void Inserttbl_VatTu(tbl_VatTu instance);
    partial void Updatetbl_VatTu(tbl_VatTu instance);
    partial void Deletetbl_VatTu(tbl_VatTu instance);
    partial void Inserttbl_DichVu(tbl_DichVu instance);
    partial void Updatetbl_DichVu(tbl_DichVu instance);
    partial void Deletetbl_DichVu(tbl_DichVu instance);
    partial void Inserttbl_HoaDon(tbl_HoaDon instance);
    partial void Updatetbl_HoaDon(tbl_HoaDon instance);
    partial void Deletetbl_HoaDon(tbl_HoaDon instance);
    partial void Inserttbl_HopDong(tbl_HopDong instance);
    partial void Updatetbl_HopDong(tbl_HopDong instance);
    partial void Deletetbl_HopDong(tbl_HopDong instance);
    partial void Inserttbl_Phong(tbl_Phong instance);
    partial void Updatetbl_Phong(tbl_Phong instance);
    partial void Deletetbl_Phong(tbl_Phong instance);
    #endregion
		
		public DBQuanLiKhachSanDataContext() : 
				base(global::QUANLIKHACHSAN.Properties.Settings.Default.DB_Doi7_3_ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBQuanLiKhachSanDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBQuanLiKhachSanDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBQuanLiKhachSanDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBQuanLiKhachSanDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_CTHoaDon> tbl_CTHoaDons
		{
			get
			{
				return this.GetTable<tbl_CTHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<tbl_VatTu> tbl_VatTus
		{
			get
			{
				return this.GetTable<tbl_VatTu>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DichVu> tbl_DichVus
		{
			get
			{
				return this.GetTable<tbl_DichVu>();
			}
		}
		
		public System.Data.Linq.Table<tbl_HoaDon> tbl_HoaDons
		{
			get
			{
				return this.GetTable<tbl_HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<tbl_HopDong> tbl_HopDongs
		{
			get
			{
				return this.GetTable<tbl_HopDong>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Phong> tbl_Phongs
		{
			get
			{
				return this.GetTable<tbl_Phong>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_CTHoaDon")]
	public partial class tbl_CTHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHD;
		
		private string _MaDV;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _GiaTIen;
		
		private EntityRef<tbl_DichVu> _tbl_DichVu;
		
		private EntityRef<tbl_HoaDon> _tbl_HoaDon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(int value);
    partial void OnMaHDChanged();
    partial void OnMaDVChanging(string value);
    partial void OnMaDVChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnGiaTIenChanging(System.Nullable<decimal> value);
    partial void OnGiaTIenChanged();
    #endregion
		
		public tbl_CTHoaDon()
		{
			this._tbl_DichVu = default(EntityRef<tbl_DichVu>);
			this._tbl_HoaDon = default(EntityRef<tbl_HoaDon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					if (this._tbl_HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					if (this._tbl_DichVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTIen", DbType="Money")]
		public System.Nullable<decimal> GiaTIen
		{
			get
			{
				return this._GiaTIen;
			}
			set
			{
				if ((this._GiaTIen != value))
				{
					this.OnGiaTIenChanging(value);
					this.SendPropertyChanging();
					this._GiaTIen = value;
					this.SendPropertyChanged("GiaTIen");
					this.OnGiaTIenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_DichVu_tbl_CTHoaDon", Storage="_tbl_DichVu", ThisKey="MaDV", OtherKey="MaDV", IsForeignKey=true)]
		public tbl_DichVu tbl_DichVu
		{
			get
			{
				return this._tbl_DichVu.Entity;
			}
			set
			{
				tbl_DichVu previousValue = this._tbl_DichVu.Entity;
				if (((previousValue != value) 
							|| (this._tbl_DichVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_DichVu.Entity = null;
						previousValue.tbl_CTHoaDons.Remove(this);
					}
					this._tbl_DichVu.Entity = value;
					if ((value != null))
					{
						value.tbl_CTHoaDons.Add(this);
						this._MaDV = value.MaDV;
					}
					else
					{
						this._MaDV = default(string);
					}
					this.SendPropertyChanged("tbl_DichVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_HoaDon_tbl_CTHoaDon", Storage="_tbl_HoaDon", ThisKey="MaHD", OtherKey="MaHD", IsForeignKey=true)]
		public tbl_HoaDon tbl_HoaDon
		{
			get
			{
				return this._tbl_HoaDon.Entity;
			}
			set
			{
				tbl_HoaDon previousValue = this._tbl_HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._tbl_HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_HoaDon.Entity = null;
						previousValue.tbl_CTHoaDons.Remove(this);
					}
					this._tbl_HoaDon.Entity = value;
					if ((value != null))
					{
						value.tbl_CTHoaDons.Add(this);
						this._MaHD = value.MaHD;
					}
					else
					{
						this._MaHD = default(int);
					}
					this.SendPropertyChanged("tbl_HoaDon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_VatTu")]
	public partial class tbl_VatTu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhong;
		
		private string _MaVatTu;
		
		private string _TenVatTu;
		
		private System.Nullable<int> _SoLuong;
		
		private string _GhiChu;
		
		private EntityRef<tbl_Phong> _tbl_Phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongChanging(string value);
    partial void OnMaPhongChanged();
    partial void OnMaVatTuChanging(string value);
    partial void OnMaVatTuChanged();
    partial void OnTenVatTuChanging(string value);
    partial void OnTenVatTuChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public tbl_VatTu()
		{
			this._tbl_Phong = default(EntityRef<tbl_Phong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					if (this._tbl_Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVatTu", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaVatTu
		{
			get
			{
				return this._MaVatTu;
			}
			set
			{
				if ((this._MaVatTu != value))
				{
					this.OnMaVatTuChanging(value);
					this.SendPropertyChanging();
					this._MaVatTu = value;
					this.SendPropertyChanged("MaVatTu");
					this.OnMaVatTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVatTu", DbType="NVarChar(50)")]
		public string TenVatTu
		{
			get
			{
				return this._TenVatTu;
			}
			set
			{
				if ((this._TenVatTu != value))
				{
					this.OnTenVatTuChanging(value);
					this.SendPropertyChanging();
					this._TenVatTu = value;
					this.SendPropertyChanged("TenVatTu");
					this.OnTenVatTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Phong_tbl_VatTu", Storage="_tbl_Phong", ThisKey="MaPhong", OtherKey="MaPhong", IsForeignKey=true)]
		public tbl_Phong tbl_Phong
		{
			get
			{
				return this._tbl_Phong.Entity;
			}
			set
			{
				tbl_Phong previousValue = this._tbl_Phong.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Phong.Entity = null;
						previousValue.tbl_VatTus.Remove(this);
					}
					this._tbl_Phong.Entity = value;
					if ((value != null))
					{
						value.tbl_VatTus.Add(this);
						this._MaPhong = value.MaPhong;
					}
					else
					{
						this._MaPhong = default(string);
					}
					this.SendPropertyChanged("tbl_Phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DichVu")]
	public partial class tbl_DichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDV;
		
		private string _TenDV;
		
		private System.Nullable<decimal> _SoTien;
		
		private string _GhiChu;
		
		private EntitySet<tbl_CTHoaDon> _tbl_CTHoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDVChanging(string value);
    partial void OnMaDVChanged();
    partial void OnTenDVChanging(string value);
    partial void OnTenDVChanged();
    partial void OnSoTienChanging(System.Nullable<decimal> value);
    partial void OnSoTienChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public tbl_DichVu()
		{
			this._tbl_CTHoaDons = new EntitySet<tbl_CTHoaDon>(new Action<tbl_CTHoaDon>(this.attach_tbl_CTHoaDons), new Action<tbl_CTHoaDon>(this.detach_tbl_CTHoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDV", DbType="NVarChar(MAX)")]
		public string TenDV
		{
			get
			{
				return this._TenDV;
			}
			set
			{
				if ((this._TenDV != value))
				{
					this.OnTenDVChanging(value);
					this.SendPropertyChanging();
					this._TenDV = value;
					this.SendPropertyChanged("TenDV");
					this.OnTenDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="Money")]
		public System.Nullable<decimal> SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this.OnSoTienChanging(value);
					this.SendPropertyChanging();
					this._SoTien = value;
					this.SendPropertyChanged("SoTien");
					this.OnSoTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_DichVu_tbl_CTHoaDon", Storage="_tbl_CTHoaDons", ThisKey="MaDV", OtherKey="MaDV")]
		public EntitySet<tbl_CTHoaDon> tbl_CTHoaDons
		{
			get
			{
				return this._tbl_CTHoaDons;
			}
			set
			{
				this._tbl_CTHoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_CTHoaDons(tbl_CTHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tbl_DichVu = this;
		}
		
		private void detach_tbl_CTHoaDons(tbl_CTHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tbl_DichVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_HoaDon")]
	public partial class tbl_HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHD;
		
		private string _MaNV;
		
		private System.Nullable<int> _MaSuKien;
		
		private string _MaHopDong;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private System.Nullable<decimal> _TienGIam;
		
		private System.Nullable<decimal> _TienPhat;
		
		private System.Nullable<decimal> _SoTienTra;
		
		private System.Nullable<decimal> _TongTien;
		
		private string _GhiChu;
		
		private EntitySet<tbl_CTHoaDon> _tbl_CTHoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(int value);
    partial void OnMaHDChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnMaSuKienChanging(System.Nullable<int> value);
    partial void OnMaSuKienChanged();
    partial void OnMaHopDongChanging(string value);
    partial void OnMaHopDongChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnTienGIamChanging(System.Nullable<decimal> value);
    partial void OnTienGIamChanged();
    partial void OnTienPhatChanging(System.Nullable<decimal> value);
    partial void OnTienPhatChanged();
    partial void OnSoTienTraChanging(System.Nullable<decimal> value);
    partial void OnSoTienTraChanged();
    partial void OnTongTienChanging(System.Nullable<decimal> value);
    partial void OnTongTienChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public tbl_HoaDon()
		{
			this._tbl_CTHoaDons = new EntitySet<tbl_CTHoaDon>(new Action<tbl_CTHoaDon>(this.attach_tbl_CTHoaDons), new Action<tbl_CTHoaDon>(this.detach_tbl_CTHoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSuKien", DbType="Int")]
		public System.Nullable<int> MaSuKien
		{
			get
			{
				return this._MaSuKien;
			}
			set
			{
				if ((this._MaSuKien != value))
				{
					this.OnMaSuKienChanging(value);
					this.SendPropertyChanging();
					this._MaSuKien = value;
					this.SendPropertyChanged("MaSuKien");
					this.OnMaSuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="NVarChar(50)")]
		public string MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienGIam", DbType="Money")]
		public System.Nullable<decimal> TienGIam
		{
			get
			{
				return this._TienGIam;
			}
			set
			{
				if ((this._TienGIam != value))
				{
					this.OnTienGIamChanging(value);
					this.SendPropertyChanging();
					this._TienGIam = value;
					this.SendPropertyChanged("TienGIam");
					this.OnTienGIamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienPhat", DbType="Money")]
		public System.Nullable<decimal> TienPhat
		{
			get
			{
				return this._TienPhat;
			}
			set
			{
				if ((this._TienPhat != value))
				{
					this.OnTienPhatChanging(value);
					this.SendPropertyChanging();
					this._TienPhat = value;
					this.SendPropertyChanged("TienPhat");
					this.OnTienPhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienTra", DbType="Money")]
		public System.Nullable<decimal> SoTienTra
		{
			get
			{
				return this._SoTienTra;
			}
			set
			{
				if ((this._SoTienTra != value))
				{
					this.OnSoTienTraChanging(value);
					this.SendPropertyChanging();
					this._SoTienTra = value;
					this.SendPropertyChanged("SoTienTra");
					this.OnSoTienTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Money")]
		public System.Nullable<decimal> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_HoaDon_tbl_CTHoaDon", Storage="_tbl_CTHoaDons", ThisKey="MaHD", OtherKey="MaHD")]
		public EntitySet<tbl_CTHoaDon> tbl_CTHoaDons
		{
			get
			{
				return this._tbl_CTHoaDons;
			}
			set
			{
				this._tbl_CTHoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_CTHoaDons(tbl_CTHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tbl_HoaDon = this;
		}
		
		private void detach_tbl_CTHoaDons(tbl_CTHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tbl_HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_HopDong")]
	public partial class tbl_HopDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHopDong;
		
		private string _MaPhong;
		
		private string _TenKhachHang;
		
		private string _SoDienThoai;
		
		private System.Nullable<System.DateTime> _NgayVao;
		
		private System.Nullable<System.DateTime> _NgayRa;
		
		private System.Nullable<decimal> _GIaThue;
		
		private string _CCCD;
		
		private bool _DaKetThuc;
		
		private EntityRef<tbl_Phong> _tbl_Phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHopDongChanging(string value);
    partial void OnMaHopDongChanged();
    partial void OnMaPhongChanging(string value);
    partial void OnMaPhongChanged();
    partial void OnTenKhachHangChanging(string value);
    partial void OnTenKhachHangChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnNgayVaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayVaoChanged();
    partial void OnNgayRaChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayRaChanged();
    partial void OnGIaThueChanging(System.Nullable<decimal> value);
    partial void OnGIaThueChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnDaKetThucChanging(bool value);
    partial void OnDaKetThucChanged();
    #endregion
		
		public tbl_HopDong()
		{
			this._tbl_Phong = default(EntityRef<tbl_Phong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="NVarChar(50)")]
		public string MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					if (this._tbl_Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(50)")]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this.OnTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenKhachHang = value;
					this.SendPropertyChanged("TenKhachHang");
					this.OnTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(10)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayVao", DbType="Date")]
		public System.Nullable<System.DateTime> NgayVao
		{
			get
			{
				return this._NgayVao;
			}
			set
			{
				if ((this._NgayVao != value))
				{
					this.OnNgayVaoChanging(value);
					this.SendPropertyChanging();
					this._NgayVao = value;
					this.SendPropertyChanged("NgayVao");
					this.OnNgayVaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayRa", DbType="Date")]
		public System.Nullable<System.DateTime> NgayRa
		{
			get
			{
				return this._NgayRa;
			}
			set
			{
				if ((this._NgayRa != value))
				{
					this.OnNgayRaChanging(value);
					this.SendPropertyChanging();
					this._NgayRa = value;
					this.SendPropertyChanged("NgayRa");
					this.OnNgayRaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIaThue", DbType="Money")]
		public System.Nullable<decimal> GIaThue
		{
			get
			{
				return this._GIaThue;
			}
			set
			{
				if ((this._GIaThue != value))
				{
					this.OnGIaThueChanging(value);
					this.SendPropertyChanging();
					this._GIaThue = value;
					this.SendPropertyChanged("GIaThue");
					this.OnGIaThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="NVarChar(MAX)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaKetThuc", DbType="Bit NOT NULL")]
		public bool DaKetThuc
		{
			get
			{
				return this._DaKetThuc;
			}
			set
			{
				if ((this._DaKetThuc != value))
				{
					this.OnDaKetThucChanging(value);
					this.SendPropertyChanging();
					this._DaKetThuc = value;
					this.SendPropertyChanged("DaKetThuc");
					this.OnDaKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Phong_tbl_HopDong", Storage="_tbl_Phong", ThisKey="MaPhong", OtherKey="MaPhong", IsForeignKey=true)]
		public tbl_Phong tbl_Phong
		{
			get
			{
				return this._tbl_Phong.Entity;
			}
			set
			{
				tbl_Phong previousValue = this._tbl_Phong.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Phong.Entity = null;
						previousValue.tbl_HopDongs.Remove(this);
					}
					this._tbl_Phong.Entity = value;
					if ((value != null))
					{
						value.tbl_HopDongs.Add(this);
						this._MaPhong = value.MaPhong;
					}
					else
					{
						this._MaPhong = default(string);
					}
					this.SendPropertyChanged("tbl_Phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Phong")]
	public partial class tbl_Phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhong;
		
		private string _TenPhong;
		
		private string _LoaiPhong;
		
		private System.Nullable<decimal> _GiaPhong;
		
		private System.Nullable<int> _TrangThai;
		
		private EntitySet<tbl_VatTu> _tbl_VatTus;
		
		private EntitySet<tbl_HopDong> _tbl_HopDongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongChanging(string value);
    partial void OnMaPhongChanged();
    partial void OnTenPhongChanging(string value);
    partial void OnTenPhongChanged();
    partial void OnLoaiPhongChanging(string value);
    partial void OnLoaiPhongChanged();
    partial void OnGiaPhongChanging(System.Nullable<decimal> value);
    partial void OnGiaPhongChanged();
    partial void OnTrangThaiChanging(System.Nullable<int> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public tbl_Phong()
		{
			this._tbl_VatTus = new EntitySet<tbl_VatTu>(new Action<tbl_VatTu>(this.attach_tbl_VatTus), new Action<tbl_VatTu>(this.detach_tbl_VatTus));
			this._tbl_HopDongs = new EntitySet<tbl_HopDong>(new Action<tbl_HopDong>(this.attach_tbl_HopDongs), new Action<tbl_HopDong>(this.detach_tbl_HopDongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhong", DbType="NVarChar(50)")]
		public string TenPhong
		{
			get
			{
				return this._TenPhong;
			}
			set
			{
				if ((this._TenPhong != value))
				{
					this.OnTenPhongChanging(value);
					this.SendPropertyChanging();
					this._TenPhong = value;
					this.SendPropertyChanged("TenPhong");
					this.OnTenPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiPhong", DbType="NVarChar(50)")]
		public string LoaiPhong
		{
			get
			{
				return this._LoaiPhong;
			}
			set
			{
				if ((this._LoaiPhong != value))
				{
					this.OnLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._LoaiPhong = value;
					this.SendPropertyChanged("LoaiPhong");
					this.OnLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaPhong", DbType="Money")]
		public System.Nullable<decimal> GiaPhong
		{
			get
			{
				return this._GiaPhong;
			}
			set
			{
				if ((this._GiaPhong != value))
				{
					this.OnGiaPhongChanging(value);
					this.SendPropertyChanging();
					this._GiaPhong = value;
					this.SendPropertyChanged("GiaPhong");
					this.OnGiaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Phong_tbl_VatTu", Storage="_tbl_VatTus", ThisKey="MaPhong", OtherKey="MaPhong")]
		public EntitySet<tbl_VatTu> tbl_VatTus
		{
			get
			{
				return this._tbl_VatTus;
			}
			set
			{
				this._tbl_VatTus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Phong_tbl_HopDong", Storage="_tbl_HopDongs", ThisKey="MaPhong", OtherKey="MaPhong")]
		public EntitySet<tbl_HopDong> tbl_HopDongs
		{
			get
			{
				return this._tbl_HopDongs;
			}
			set
			{
				this._tbl_HopDongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_VatTus(tbl_VatTu entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Phong = this;
		}
		
		private void detach_tbl_VatTus(tbl_VatTu entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Phong = null;
		}
		
		private void attach_tbl_HopDongs(tbl_HopDong entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Phong = this;
		}
		
		private void detach_tbl_HopDongs(tbl_HopDong entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Phong = null;
		}
	}
}
#pragma warning restore 1591
